import pygame
import random

# TILES
DIRT = 0
GRASS = 1
WATER = 2

class Tree:
    def __init__(self):
        self.SPRITE = pygame.transform.scale(pygame.image.load('textures/trees/tree.png'), (125, 125))
        self.X_POS = random.randint(50, 300)
        self.Y_POS = random.randint(50, 450)

# DICTIONARY LINKING TILES TO THEIR COLORS pygame.image.load('pic.png')
TEXTURES = {
    DIRT: pygame.image.load('textures/dirt.png'),
    GRASS: pygame.image.load('textures/grass.png'),
    WATER: pygame.image.load('textures/water.png')
}

# TILES TO BE DISPLAYED
GRID = [
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WATER, WATER, WATER],
    [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, WATER, WATER, WATER, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, DIRT, DIRT, WATER, WATER, GRASS, GRASS, GRASS],
    [GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, WATER, DIRT, GRASS, GRASS, GRASS, GRASS, GRASS],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, GRASS, GRASS, GRASS],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS]
]

# GRID[kolumna][wiersz]
print(GRID[-4][0])

# GAME DIMENSIONS, CONFIG
TILESIZE = 64
MAPWIDTH = 20
MAPHEIGHT = 10
pygame.init()
pygame.display.set_caption('PYGAME GAME')
# MAPHEIGHT + 125 for inventory
window = pygame.display.set_mode((MAPWIDTH*TILESIZE, MAPHEIGHT*TILESIZE))
#window = pygame.display.set_mode((512,320))    // mniejsza mapa i potem próba przesuwania 